# This is a config for E2B sandbox template.
# You can use template ID (c37betn7e5ftnmsdh8cw) or template name (code0-nextjsradixui) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("code0-nextjsradixui") # Sync sandbox
# sandbox = await AsyncSandbox.create("code0-nextjsradixui") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('code0-nextjsradixui')

team_id = "4465cfe3-5234-4e68-8099-a4df2df45079"
memory_mb = 8_192
cpu_count = 8
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "code0-nextjsradixui"
template_id = "c37betn7e5ftnmsdh8cw"
