name: Publish Templates

on:
  workflow_run:
    workflows: ["Build Templates"]
    types:
      - completed
    branches:
      - master

concurrency:
  group: publish-templates-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install E2B CLI
        run: npm i -g @e2b/cli

      - name: Verify e2b install
        run: e2b --version

      - name: Publish All Templates
        env:
          E2B_ACCESS_TOKEN: ${{ secrets.E2B_ACCESS_TOKEN }}
        run: |
          node ./scripts/build-and-publish.mjs --mode publish
